services:
    tahoe.multi_tenancy.invitation_factory:
        class: Tahoe\Bundle\MultiTenancyBundle\Factory\InvitationFactory
    invitation_factory:
        alias: tahoe.multi_tenancy.invitation_factory

    tahoe.multi_tenancy.tenant_user_factory:
        class: Tahoe\Bundle\MultiTenancyBundle\Factory\TenantUserFactory

    tahoe.multi_tenancy.tenant.factory:
        class: Tahoe\Bundle\MultiTenancyBundle\Factory\TenantFactory
        arguments: [%tahoe_multi_tenancy.tenant.class%]

    tenant_user_factory:
        alias: tahoe.multi_tenancy.tenant_user_factory